digraph "CFG forkotlinx.coroutines.JobSupport.getChildJobCancellationCause()Ljava\/util\/concurrent\/CancellationException;" {
Node_20 [shape=record,label="{20\:\ ?|MTH_ENTER_BLOCK\l}"];
Node_22 [shape=record,label="{22\:\ 0x0000|java.lang.Object r0 = getState$kotlinx_coroutines_core()\lr2 = null\l}"];
Node_23 [shape=record,label="{23\:\ 0x0008|if ((r0 instanceof kotlinx.coroutines.JobSupport.Finishing) == false) goto L12\l}"];
Node_24 [shape=record,label="{24\:\ 0x000a|java.lang.Throwable r1 = ((kotlinx.coroutines.JobSupport.Finishing) r0).getRootCause()\l}"];
Node_31 [shape=record,label="{31\:\ 0x0021|PHI: r1 \l  PHI: (r1v8 'rootCause' java.lang.Throwable) = (r1v4 'rootCause' java.lang.Throwable), (r1v7 'rootCause' java.lang.Throwable), (r1v11 'rootCause' java.lang.Throwable) binds: [B:30:0x0020, B:27:0x0016, B:24:0x000a] A[DONT_GENERATE, DONT_INLINE]\l}"];
Node_32 [shape=record,label="{32\:\ 0x0024|if ((r1 instanceof java.util.concurrent.CancellationException) == false) goto L7\l}"];
Node_33 [shape=record,label="{33\:\ 0x0026|java.util.concurrent.CancellationException r2 = r1\l}"];
Node_34 [shape=record,label="{34\:\ 0x0029|PHI: r2 \l  PHI: (r2v4 java.util.concurrent.CancellationException) = (r2v0 java.util.concurrent.CancellationException), (r2v8 java.util.concurrent.CancellationException) binds: [B:32:0x0024, B:33:0x0026] A[DONT_GENERATE, DONT_INLINE]\l|if (r2 != null) goto L11\l}"];
Node_35 [shape=record,label="{35\:\ 0x002b}"];
Node_36 [shape=record,label="{36\:\ 0x003f|RETURN\lORIG_RETURN\l|return new kotlinx.coroutines.JobCancellationException(kotlin.jvm.internal.Intrinsics.stringPlus(\"Parent job is \", stateString(r0)), r1, r5)\l}"];
Node_21 [shape=record,label="{21\:\ ?|MTH_EXIT_BLOCK\l}"];
Node_39 [shape=record,label="{39\:\ ?|SYNTHETIC\lRETURN\l|return r2\l}"];
Node_25 [shape=record,label="{25\:\ 0x0012}"];
Node_26 [shape=record,label="{26\:\ 0x0014|if ((r0 instanceof kotlinx.coroutines.CompletedExceptionally) == false) goto L15\l}"];
Node_27 [shape=record,label="{27\:\ 0x0016|java.lang.Throwable r1 = ((kotlinx.coroutines.CompletedExceptionally) r0).cause\l}"];
Node_28 [shape=record,label="{28\:\ 0x001c}"];
Node_29 [shape=record,label="{29\:\ 0x001e|if ((r0 instanceof kotlinx.coroutines.Incomplete) != false) goto L18\l}"];
Node_30 [shape=record,label="{30\:\ 0x0020|r1 = null\l}"];
Node_37 [shape=record,label="{37\:\ 0x0040}"];
Node_38 [shape=record,label="{38\:\ 0x004f|throw new java.lang.IllegalStateException(kotlin.jvm.internal.Intrinsics.stringPlus(\"Cannot be cancelling child in this state: \", r0).toString())\l}"];
MethodNode[shape=record,label="{public java.util.concurrent.CancellationException kotlinx.coroutines.JobSupport.getChildJobCancellationCause((r5v0 'this' kotlinx.coroutines.JobSupport A[IMMUTABLE_TYPE, THIS]))  | USE_LINES_HINTS\lCROSS_EDGE: B:34:0x0029 \-\> B:36:0x003f, CROSS_EDGE: B:32:0x0024 \-\> B:34:0x0029, CROSS_EDGE: B:27:0x0016 \-\> B:31:0x0021, CROSS_EDGE: B:30:0x0020 \-\> B:31:0x0021, CROSS_EDGE: B:38:0x004f \-\> B:21:?\lINLINE_NOT_NEEDED\lTYPE_VARS: EMPTY\lMETHOD_OVERRIDE: [kotlinx.coroutines.ParentJob.getChildJobCancellationCause():java.util.concurrent.CancellationException]\l}"];
MethodNode -> Node_20;Node_20 -> Node_22;
Node_22 -> Node_23;
Node_23 -> Node_24[style=dashed];
Node_23 -> Node_25;
Node_24 -> Node_31;
Node_31 -> Node_32;
Node_32 -> Node_33[style=dashed];
Node_32 -> Node_34;
Node_33 -> Node_34;
Node_34 -> Node_35[style=dashed];
Node_34 -> Node_39;
Node_35 -> Node_36;
Node_36 -> Node_21;
Node_39 -> Node_21;
Node_25 -> Node_26;
Node_26 -> Node_27[style=dashed];
Node_26 -> Node_28;
Node_27 -> Node_31;
Node_28 -> Node_29;
Node_29 -> Node_30[style=dashed];
Node_29 -> Node_37;
Node_30 -> Node_31;
Node_37 -> Node_38;
Node_38 -> Node_21;
}

