digraph "CFG forkotlinx.coroutines.DispatchedTask.handleFatalException(Ljava\/lang\/Throwable;Ljava\/lang\/Throwable;)V" {
Node_13 [shape=record,label="{13\:\ ?|MTH_ENTER_BLOCK\l}"];
Node_15 [shape=record,label="{15\:\ 0x0000|0x0000: IF  (r5 I:??[int, boolean, OBJECT, ARRAY, byte, short, char] A[D('exception' java.lang.Throwable)]) != (0 ??[int, boolean, OBJECT, ARRAY, byte, short, char])  \-\> B:18:0x0005  (LINE:138)\l}"];
Node_16 [shape=record,label="{16\:\ 0x0002|0x0002: IF  (r6 I:??[int, boolean, OBJECT, ARRAY, byte, short, char] A[D('finallyException' java.lang.Throwable)]) != (0 ??[int, boolean, OBJECT, ARRAY, byte, short, char])  \-\> B:18:0x0005 \l}"];
Node_17 [shape=record,label="{17\:\ 0x0004|RETURN\l|0x0004: RETURN   \l}"];
Node_14 [shape=record,label="{14\:\ ?|MTH_EXIT_BLOCK\l}"];
Node_18 [shape=record,label="{18\:\ 0x0005|0x0005: IF  (r5 I:??[int, boolean, OBJECT, ARRAY, byte, short, char] A[D('exception' java.lang.Throwable)]) == (0 ??[int, boolean, OBJECT, ARRAY, byte, short, char])  \-\> B:21:0x000e  (LINE:139)\l}"];
Node_19 [shape=record,label="{19\:\ 0x0007|0x0007: IF  (r6 I:??[int, boolean, OBJECT, ARRAY, byte, short, char] A[D('finallyException' java.lang.Throwable)]) == (0 ??[int, boolean, OBJECT, ARRAY, byte, short, char])  \-\> B:21:0x000e \l}"];
Node_20 [shape=record,label="{20\:\ 0x0009|0x0009: MOVE  (r0 I:??[OBJECT, ARRAY]) = (r5 I:??[OBJECT, ARRAY] A[D('exception' java.lang.Throwable)])  (LINE:140)\l0x000a: CONST  (r1 I:??[int, float, boolean, short, byte, char, OBJECT, ARRAY]) = (0 ??[int, float, boolean, short, byte, char, OBJECT, ARRAY]) \l0x000b: INVOKE  \l  (r0 I:java.lang.Throwable A[D('$this$addSuppressedThrowable$iv' java.lang.Throwable)])\l  (r6 I:java.lang.Throwable A[D('finallyException' java.lang.Throwable)])\l type: STATIC call: kotlin.ExceptionsKt.addSuppressed(java.lang.Throwable, java.lang.Throwable):void A[MD:(java.lang.Throwable, java.lang.Throwable):void (m)] (LINE:240)\l}"];
Node_21 [shape=record,label="{21\:\ 0x000e|0x000e: IF  (r5 I:??[int, boolean, OBJECT, ARRAY, byte, short, char] A[D('exception' java.lang.Throwable)]) != (0 ??[int, boolean, OBJECT, ARRAY, byte, short, char])  \-\> B:23:0x0012  (LINE:143)\l}"];
Node_22 [shape=record,label="{22\:\ 0x0010|0x0010: MOVE  (r0 I:??[OBJECT, ARRAY]) = (r6 I:??[OBJECT, ARRAY] A[D('finallyException' java.lang.Throwable)]) \l}"];
Node_24 [shape=record,label="{24\:\ 0x0013|0x0013: NEW_INSTANCE  (r1 I:kotlinx.coroutines.CoroutinesInternalError) =  kotlinx.coroutines.CoroutinesInternalError  (LINE:144)\l0x0015: NEW_INSTANCE  (r2 I:java.lang.StringBuilder) =  java.lang.StringBuilder \l0x0017: INVOKE  (r2 I:java.lang.StringBuilder) type: DIRECT call: java.lang.StringBuilder.\<init\>():void A[MD:():void (c)]\l0x001a: CONST_STR  (r3 I:java.lang.String) =  \"Fatal exception in coroutines machinery for \" \l0x001c: INVOKE  (r2 I:java.lang.StringBuilder), (r3 I:java.lang.String) type: VIRTUAL call: java.lang.StringBuilder.append(java.lang.String):java.lang.StringBuilder A[MD:(java.lang.String):java.lang.StringBuilder (c)]\l0x001f: INVOKE  (r2 I:java.lang.StringBuilder), (r4 I:java.lang.Object) type: VIRTUAL call: java.lang.StringBuilder.append(java.lang.Object):java.lang.StringBuilder A[MD:(java.lang.Object):java.lang.StringBuilder (c)]\l0x0022: CONST_STR  (r3 I:java.lang.String) =  \". Please read KDoc to 'handleFatalException' method and report this incident to maintainers\" \l0x0024: INVOKE  (r2 I:java.lang.StringBuilder), (r3 I:java.lang.String) type: VIRTUAL call: java.lang.StringBuilder.append(java.lang.String):java.lang.StringBuilder A[MD:(java.lang.String):java.lang.StringBuilder (c)]\l0x0027: INVOKE  (r2 I:java.lang.String) = (r2 I:java.lang.StringBuilder) type: VIRTUAL call: java.lang.StringBuilder.toString():java.lang.String A[MD:():java.lang.String (c)]\l0x002b: INVOKE  (r0 I:java.lang.Object A[D('cause' java.lang.Throwable)]) type: STATIC call: kotlin.jvm.internal.Intrinsics.checkNotNull(java.lang.Object):void A[MD:(java.lang.Object):void (m)] (LINE:145)\l0x002e: INVOKE  \l  (r1 I:kotlinx.coroutines.CoroutinesInternalError)\l  (r2 I:java.lang.String)\l  (r0 I:java.lang.Throwable A[D('cause' java.lang.Throwable)])\l type: DIRECT call: kotlinx.coroutines.CoroutinesInternalError.\<init\>(java.lang.String, java.lang.Throwable):void A[MD:(java.lang.String, java.lang.Throwable):void (m)] (LINE:144)\l0x0031: INVOKE  (r2 I:kotlin.coroutines.Continuation) = (r4 I:kotlinx.coroutines.DispatchedTask) type: VIRTUAL call: kotlinx.coroutines.DispatchedTask.getDelegate$kotlinx_coroutines_core():kotlin.coroutines.Continuation A[MD:():kotlin.coroutines.Continuation\<T\> (m)] (LINE:146)\l0x0035: INVOKE  (r2 I:kotlin.coroutines.CoroutineContext) = (r2 I:kotlin.coroutines.Continuation) type: INTERFACE call: kotlin.coroutines.Continuation.getContext():kotlin.coroutines.CoroutineContext A[MD:():kotlin.coroutines.CoroutineContext (m)]\l0x0039: MOVE  (r3 I:??[OBJECT, ARRAY]) = (r1 I:??[OBJECT, ARRAY] A[D('reason' kotlinx.coroutines.CoroutinesInternalError)]) \l0x003a: CHECK_CAST (r3 I:java.lang.Throwable) = (java.lang.Throwable) (r3 I:??[OBJECT, ARRAY]) \l0x003c: INVOKE  (r2 I:kotlin.coroutines.CoroutineContext), (r3 I:java.lang.Throwable) type: STATIC call: kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(kotlin.coroutines.CoroutineContext, java.lang.Throwable):void A[MD:(kotlin.coroutines.CoroutineContext, java.lang.Throwable):void (m)]\l}"];
Node_25 [shape=record,label="{25\:\ 0x003f|RETURN\l|0x003f: RETURN    (LINE:147)\l}"];
Node_23 [shape=record,label="{23\:\ 0x0012|0x0012: MOVE  (r0 I:??[OBJECT, ARRAY]) = (r5 I:??[OBJECT, ARRAY] A[D('exception' java.lang.Throwable)]) \l}"];
MethodNode[shape=record,label="{public final void kotlinx.coroutines.DispatchedTask.handleFatalException((r4 'this' I:kotlinx.coroutines.DispatchedTask\<T\> A[IMMUTABLE_TYPE, THIS]), (r5 I:java.lang.Throwable A[D('exception' java.lang.Throwable), IMMUTABLE_TYPE, METHOD_ARGUMENT]), (r6 I:java.lang.Throwable A[D('finallyException' java.lang.Throwable), IMMUTABLE_TYPE, METHOD_ARGUMENT]))  | USE_LINES_HINTS\lCROSS_EDGE: B:25:0x003f \-\> B:14:?, CROSS_EDGE: B:23:0x0012 \-\> B:24:0x0013, CROSS_EDGE: B:19:0x0007 \-\> B:21:0x000e, CROSS_EDGE: B:18:0x0005 \-\> B:21:0x000e, CROSS_EDGE: B:15:0x0000 \-\> B:18:0x0005\lINLINE_NOT_NEEDED\lDebug Info:\l  0x000a\-0x000e: r0 '$this$addSuppressedThrowable$iv' Ljava\/lang\/Throwable;\l  0x000b\-0x000e: r1 '$i$f$addSuppressedThrowable' I\l  0x0013\-0x003f: r0 'cause' Ljava\/lang\/Throwable;\l  0x0031\-0x003f: r1 'reason' Lkotlinx\/coroutines\/CoroutinesInternalError;\l  \-1 \-0x003f: r5 'exception' Ljava\/lang\/Throwable;\l  \-1 \-0x003f: r6 'finallyException' Ljava\/lang\/Throwable;\lTYPE_VARS: [T]\l}"];
MethodNode -> Node_13;Node_13 -> Node_15;
Node_15 -> Node_16[style=dashed];
Node_15 -> Node_18;
Node_16 -> Node_17[style=dashed];
Node_16 -> Node_18;
Node_17 -> Node_14;
Node_18 -> Node_19[style=dashed];
Node_18 -> Node_21;
Node_19 -> Node_20[style=dashed];
Node_19 -> Node_21;
Node_20 -> Node_21;
Node_21 -> Node_22[style=dashed];
Node_21 -> Node_23;
Node_22 -> Node_24;
Node_24 -> Node_25;
Node_25 -> Node_14;
Node_23 -> Node_24;
}

