digraph "CFG forkotlin.jvm.internal.ArrayCharIterator.nextChar()C" {
Node_9 [shape=record,label="{9\:\ ?|MTH_ENTER_BLOCK\l}"];
Node_16 [shape=record,label="{16\:\ 0x0000|SYNTHETIC\lEXC_TOP_SPLITTER\l}"];
Node_11 [shape=record,label="{11\:\ 0x0000|TRY_ENTER\lTRY_LEAVE\lTryCatch #0 \{ArrayIndexOutOfBoundsException \-\> 0x000b, blocks: (B:11:0x0000), top: B:16:0x0000 \}\lCatch: ArrayIndexOutOfBoundsException \-\> 0x000b\l|0x0000: IGET  (r0 I:char[]) = (r3 I:kotlin.jvm.internal.ArrayCharIterator) kotlin.jvm.internal.ArrayCharIterator.array char[] A[Catch: ArrayIndexOutOfBoundsException \-\> 0x000b, TRY_ENTER] (LINE:19)\l0x0002: IGET  (r1 I:int) = (r3 I:kotlin.jvm.internal.ArrayCharIterator) kotlin.jvm.internal.ArrayCharIterator.index int A[Catch: ArrayIndexOutOfBoundsException \-\> 0x000b]\l0x0004: ARITH  (r2 I:int) = (r1 I:int) + (1 int) A[Catch: ArrayIndexOutOfBoundsException \-\> 0x000b]\l0x0006: IPUT  (r2 I:int), (r3 I:kotlin.jvm.internal.ArrayCharIterator) kotlin.jvm.internal.ArrayCharIterator.index int A[Catch: ArrayIndexOutOfBoundsException \-\> 0x000b]\l0x0008: AGET  (r0 I:char A[IMMUTABLE_TYPE]) = (r0 I:char[] A[IMMUTABLE_TYPE]), (r1 I:??[int, short, byte, char]) A[Catch: ArrayIndexOutOfBoundsException \-\> 0x000b, TRY_LEAVE]\l}"];
Node_12 [shape=record,label="{12\:\ 0x000a|RETURN\l|0x000a: RETURN  (r0 I:char) \l}"];
Node_10 [shape=record,label="{10\:\ ?|MTH_EXIT_BLOCK\l}"];
Node_17 [shape=record,label="{17\:\ ?|SYNTHETIC\lEXC_BOTTOM_SPLITTER\l}"];
Node_13 [shape=record,label="{13\:\ 0x000b|ExcHandler: ArrayIndexOutOfBoundsException \-\> 0x000b\l|0x000b: MOVE_EXCEPTION  (r0 I:java.lang.ArrayIndexOutOfBoundsException A[CUSTOM_DECLARE]) =  A[DONT_INLINE, ExcHandler: ArrayIndexOutOfBoundsException \-\> 0x000b]\l}"];
Node_14 [shape=record,label="{14\:\ 0x000c|0x000c: IGET  (r1 I:int) = (r3 I:kotlin.jvm.internal.ArrayCharIterator) kotlin.jvm.internal.ArrayCharIterator.index int \l0x000e: ARITH  (r1 I:int) = (r1 I:int) + (\-1 int) \l0x0010: IPUT  (r1 I:int), (r3 I:kotlin.jvm.internal.ArrayCharIterator) kotlin.jvm.internal.ArrayCharIterator.index int \l0x0012: NEW_INSTANCE  (r1 I:java.util.NoSuchElementException) =  java.util.NoSuchElementException \l0x0014: INVOKE  (r2 I:java.lang.String) = (r0 I:java.lang.ArrayIndexOutOfBoundsException A[D('e' java.lang.ArrayIndexOutOfBoundsException)]) type: VIRTUAL call: java.lang.ArrayIndexOutOfBoundsException.getMessage():java.lang.String A[MD:():java.lang.String (s)]\l0x0018: INVOKE  (r1 I:java.util.NoSuchElementException), (r2 I:java.lang.String) type: DIRECT call: java.util.NoSuchElementException.\<init\>(java.lang.String):void A[MD:(java.lang.String):void (c)]\l}"];
Node_15 [shape=record,label="{15\:\ 0x001b|0x001b: THROW  (r1 I:java.lang.Throwable) \l}"];
MethodNode[shape=record,label="{public char kotlin.jvm.internal.ArrayCharIterator.nextChar((r3 'this' I:kotlin.jvm.internal.ArrayCharIterator A[IMMUTABLE_TYPE, THIS]))  | USE_LINES_HINTS\lCROSS_EDGE: B:15:0x001b \-\> B:10:?, CROSS_EDGE: B:16:0x0000 \-\> B:13:0x000b\lINLINE_NOT_NEEDED\lDebug Info:\l  0x000c\-0x001b: r0 'e' Ljava\/lang\/ArrayIndexOutOfBoundsException;\lTryCatch #0 \{ArrayIndexOutOfBoundsException \-\> 0x000b, blocks: (B:11:0x0000), top: B:16:0x0000 \}\lMETHOD_OVERRIDE: [kotlin.collections.CharIterator.nextChar():char]\l}"];
MethodNode -> Node_9;Node_9 -> Node_16;
Node_16 -> Node_11;
Node_16 -> Node_13;
Node_11 -> Node_12;
Node_11 -> Node_17;
Node_12 -> Node_10;
Node_17 -> Node_13;
Node_13 -> Node_14;
Node_14 -> Node_15;
Node_15 -> Node_10;
}

