digraph "CFG forandroidx.concurrent.futures.AbstractResolvableFuture.cancellationExceptionWithCause(Ljava\/lang\/String;Ljava\/lang\/Throwable;)Ljava\/util\/concurrent\/CancellationException;" {
Node_4 [shape=record,label="{4\:\ ?|MTH_ENTER_BLOCK\l}"];
Node_6 [shape=record,label="{6\:\ 0x0000|0x0000: NEW_INSTANCE  (r0 I:java.util.concurrent.CancellationException) =  java.util.concurrent.CancellationException  (LINE:1192)\l0x0002: INVOKE  (r0 I:java.util.concurrent.CancellationException), (r1 I:java.lang.String A[D('message' java.lang.String)]) type: DIRECT call: java.util.concurrent.CancellationException.\<init\>(java.lang.String):void A[MD:(java.lang.String):void (c)]\l0x0005: INVOKE  \l  (r0 I:java.util.concurrent.CancellationException A[D('exception' java.util.concurrent.CancellationException)])\l  (r2 I:java.lang.Throwable A[D('cause' java.lang.Throwable)])\l type: VIRTUAL call: java.util.concurrent.CancellationException.initCause(java.lang.Throwable):java.lang.Throwable A[MD:(java.lang.Throwable):java.lang.Throwable (s)] (LINE:1193)\l}"];
Node_7 [shape=record,label="{7\:\ 0x0008|RETURN\l|0x0008: RETURN  (r0 I:java.util.concurrent.CancellationException A[D('exception' java.util.concurrent.CancellationException)])  (LINE:1194)\l}"];
Node_5 [shape=record,label="{5\:\ ?|MTH_EXIT_BLOCK\l}"];
MethodNode[shape=record,label="{private static java.util.concurrent.CancellationException androidx.concurrent.futures.AbstractResolvableFuture.cancellationExceptionWithCause((r1 I:java.lang.String A[D('message' java.lang.String), IMMUTABLE_TYPE, METHOD_ARGUMENT]), (r2 I:java.lang.Throwable A[D('cause' java.lang.Throwable), IMMUTABLE_TYPE, METHOD_ARGUMENT]))  | USE_LINES_HINTS\lINLINE_NOT_NEEDED\lDebug Info:\l  0x0005\-0x0008: r0 'exception' Ljava\/util\/concurrent\/CancellationException;\l  \-1 \-0x0008: r1 'message' Ljava\/lang\/String;\l  \-1 \-0x0008: r2 'cause' Ljava\/lang\/Throwable;\l}"];
MethodNode -> Node_4;Node_4 -> Node_6;
Node_6 -> Node_7;
Node_7 -> Node_5;
}

