digraph "CFG forkotlinx.coroutines.channels.BroadcastCoroutine.cancelInternal(Ljava\/lang\/Throwable;)V" {
Node_4 [shape=record,label="{4\:\ ?|MTH_ENTER_BLOCK\l}"];
Node_6 [shape=record,label="{6\:\ 0x0000|0x0000: MOVE  (r0 I:??[OBJECT, ARRAY]) = (r3 I:??[OBJECT, ARRAY])  (LINE:158)\l0x0001: CHECK_CAST (r0 I:kotlinx.coroutines.JobSupport) = (kotlinx.coroutines.JobSupport) (r0 I:??[OBJECT, ARRAY]) \l0x0003: CONST  (r1 I:??[int, float, boolean, short, byte, char, OBJECT, ARRAY]) = (0 ??[int, float, boolean, short, byte, char, OBJECT, ARRAY]) \l0x0004: CONST  (r2 I:??[boolean, int, float, short, byte, char]) = (1 ??[boolean, int, float, short, byte, char]) \l0x0005: INVOKE  (r0 I:java.util.concurrent.CancellationException) = \l  (r0 I:kotlinx.coroutines.JobSupport)\l  (r4 I:java.lang.Throwable A[D('cause' java.lang.Throwable)])\l  (r1 I:java.lang.String)\l  (r2 I:int)\l  (r1 I:java.lang.Object)\l type: STATIC call: kotlinx.coroutines.JobSupport.toCancellationException$default(kotlinx.coroutines.JobSupport, java.lang.Throwable, java.lang.String, int, java.lang.Object):java.util.concurrent.CancellationException A[MD:(kotlinx.coroutines.JobSupport, java.lang.Throwable, java.lang.String, int, java.lang.Object):java.util.concurrent.CancellationException (m)]\l0x0009: IGET  (r1 I:kotlinx.coroutines.channels.BroadcastChannel\<E\>) = (r3 I:kotlinx.coroutines.channels.BroadcastCoroutine) kotlinx.coroutines.channels.BroadcastCoroutine._channel kotlinx.coroutines.channels.BroadcastChannel  (LINE:159)\l0x000b: INVOKE  \l  (r1 I:kotlinx.coroutines.channels.BroadcastChannel)\l  (r0 I:java.util.concurrent.CancellationException A[D('exception' java.util.concurrent.CancellationException)])\l type: INTERFACE call: kotlinx.coroutines.channels.BroadcastChannel.cancel(java.util.concurrent.CancellationException):void A[MD:(java.util.concurrent.CancellationException):void (m)]\l0x000e: MOVE  (r1 I:??[OBJECT, ARRAY]) = (r0 I:??[OBJECT, ARRAY] A[D('exception' java.util.concurrent.CancellationException)])  (LINE:160)\l0x000f: CHECK_CAST (r1 I:java.lang.Throwable) = (java.lang.Throwable) (r1 I:??[OBJECT, ARRAY]) \l0x0011: INVOKE  (r3 I:kotlinx.coroutines.channels.BroadcastCoroutine), (r1 I:java.lang.Throwable) type: VIRTUAL call: kotlinx.coroutines.channels.BroadcastCoroutine.cancelCoroutine(java.lang.Throwable):boolean A[MD:(java.lang.Throwable):boolean (m)]\l}"];
Node_7 [shape=record,label="{7\:\ 0x0014|RETURN\l|0x0014: RETURN    (LINE:161)\l}"];
Node_5 [shape=record,label="{5\:\ ?|MTH_EXIT_BLOCK\l}"];
MethodNode[shape=record,label="{public void kotlinx.coroutines.channels.BroadcastCoroutine.cancelInternal((r3 'this' I:kotlinx.coroutines.channels.BroadcastCoroutine\<E\> A[IMMUTABLE_TYPE, THIS]), (r4 I:java.lang.Throwable A[D('cause' java.lang.Throwable), IMMUTABLE_TYPE, METHOD_ARGUMENT]))  | USE_LINES_HINTS\lINLINE_NOT_NEEDED\lDebug Info:\l  0x0009\-0x0014: r0 'exception' Ljava\/util\/concurrent\/CancellationException;\l  \-1 \-0x0014: r4 'cause' Ljava\/lang\/Throwable;\lTYPE_VARS: [E]\lMETHOD_OVERRIDE: [kotlinx.coroutines.JobSupport.cancelInternal(java.lang.Throwable):void]\l}"];
MethodNode -> Node_4;Node_4 -> Node_6;
Node_6 -> Node_7;
Node_7 -> Node_5;
}

